on:
   push:
     branches:
       - main
name: release-please
permissions: {}
jobs:
  release-please:
    permissions:
      contents: write # to create release commit
      pull-requests: write # to create release PR

    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install npm@latest -g

      - run: npm install
      - run: npm run prod
      - run: npm run zip

      - name: Publish to Chrome Web Store
        uses: mobilefirstllc/cws-publish@latest
        with:
          action: 'publish' 
          client_id: ${{ secrets.GOOGLE_CLIENT }}
          client_secret: ${{ secrets.GOOGLE_SECRET }}
          refresh_token: ${{ secrets.GOOGLE_TOKEN }}
          extension_id: ${{ secrets.EXTENSION_ID }}
          zip_file: 'Better-IUT-RCC.zip'
        if: ${{ steps.release.outputs.release_created }}