on:
   push:
     branches:
       - main
name: release-please
permissions: {}
jobs:
  release-please:
    permissions:
      contents: write # to create release commit
      pull-requests: write # to create release PR

    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install npm@latest -g

      - run: npm install
      - run: npm run prod
      - run: npm run zip
      
      - name: Create xpi file
        run: cp Better-IUT-RCC.zip Better-IUT-RCC.xpi

      - name: Publish to Chrome Web Store
        uses: mobilefirstllc/cws-publish@latest
        continue-on-error: true
        with:
          action: 'publish' 
          client_id: ${{ secrets.GOOGLE_CLIENT }}
          client_secret: ${{ secrets.GOOGLE_SECRET }}
          refresh_token: ${{ secrets.GOOGLE_TOKEN }}
          extension_id: ${{ secrets.EXTENSION_ID }}
          zip_file: 'Better-IUT-RCC.zip'
        if: ${{ steps.release.outputs.release_created }}

      - name: Publish to Edge Addons Store
        uses: wdzeng/edge-addon@v2
        continue-on-error: true
        with:
          product-id: ${{ secrets.EDGE_EXTENSION_ID }}
          zip-path: 'Better-IUT-RCC.zip'
          client-id: ${{ secrets.EDGE_CLIENT_ID }}
          api-key: ${{ secrets.EDGE_API_KEY }}
        if: ${{ steps.release.outputs.release_created }}
      
      - name: Create web-ext-artifacts folder
        run: mkdir web-ext-artifacts

      - name: Sign Firefox Addon
        id: web-ext-sign
        uses: kewisch/action-web-ext@v1.3
        with:
          cmd: sign
          source: 'Better-IUT-RCC.xpi'
          channel: unlisted
          apiKey: ${{ secrets.FF_JWT_ISSUER }}
          apiSecret: ${{ secrets.FF_JWT_SECRET }}
          timeout: 900000
        if: ${{ steps.release.outputs.release_created }}

      - name: Upload the signed xpi
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: ${{ steps.web-ext-sign.outputs.target }}
          asset_name: Better-IUT-RCC-${{ steps.release.outputs.tag_name }}.xpi
          asset_content_type: application/zip
        if: ${{ steps.release.outputs.release_created }}

      - name: Generate the update manifest
        uses: 2zqa/generate-update-manifest@v1
        with:
          addon-id: ${{ secrets.FF_EXTENSION_ID }}
          output-file: .ff_updates.json
          asset-filter: "*.xpi"
        if: ${{ steps.release.outputs.release_created }}
      
      - name: Commit and Push the update manifest
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .ff_updates.json
          git commit -m "Update Firefox self hosted manifest to version ${{ steps.release.outputs.tag_name }}"
          git push -u origin main
        if: ${{ steps.release.outputs.release_created }}